### ISSUE TITLE
Bumped into errors when using ASMExt

### ISSUE THREAD

**Issue by QRXqrx** [ali-ghanbari/ASM-Ext#1]
Hi,

I download your source code and try to use ASMExt.java, but it seems there is a error in your code. Screenshot here:
![image](https://user-images.githubusercontent.com/49576982/71222312-11e42c00-230b-11ea-8c63-252205412c7f.png)
I import `asm-7.0.jar` as dependency. Was there anything I did wrong? Please reply me at your convenience, thanks.

**Comment by ali-ghanbari** [comment]
Hi,

I do apologize for belated response; I had not noticed this question. Today I accidentally saw the issue that you have raised a long time ago.

At the time that I was writing this code, I was not familiar with any Build system (e.g., Ant or Maven), so that's why configuring this project happened to be rather inconvenient for others. All the dependencies are there under the folder "lib." You just need to delete invalid dependencies and reimport the JARs under "lib" folder.

I am explaining the steps that I have just taken in Eclipse IDE to resolve that problem:
1. After checking out the repo, from File menu select "Projects from Folder or Archive" and select the checked out directory and click on Finish button.
[2. Right click on the imported project and select Properties and from Java Compiler section, make sure you have selected Java level to 1.8 or higher.]
3. Right click on the imported project and from "Build Path" select "Configure Build Path". Under the "Libraries" tab delete the three erroneous JARs and reimport the JARs under the "lib" folder of the checked out repo by clicking on "Add External JARs..." button. After click on "Apply on Close" you should be good to go.

Hope these will help.

**Comment by QRXqrx** [comment]
Hey,

Thank you for replying. Since it has been a long time, I'm not focusing on your project at present. Your advice is very valuable, I will take it into consideration when I try to pick up ASM-Ext again.  I will let you know if I have any new questions. Wish you success in your work :-)
